name       : signal-desktop
version    : 1.14.4
release    : 25
source     :
    - git|https://github.com/WhisperSystems/Signal-Desktop.git : v1.14.4
license    : GPL-3.0
component  : network.im
summary    : Signal Desktop is an Electron application that links with your Signal Android or Signal iOS app.
description: |
    Signal Desktop is an Electron application that links with your Signal Android or Signal iOS app.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - yarn
setup      : |
    yarn install --ignore-engines
build      : |
    # Use npm directly since Signal opted to randomly remove the handy pack-prod.
    export SIGNAL_ENV=production
    npm run generate
    npm run build -- --dir
install    : |
    install -Dm00644 $pkgfiles/signal-desktop.desktop $installdir/usr/share/applications/signal-desktop.desktop
    # Install all the icons
    for s in 16 24 32 48 64 128 256 512; do
        install -Dm00644 build/icons/png/${s}x${s}.png $installdir/usr/share/icons/hicolor/${s}x${s}/apps/signal-desktop.png
    done
    install -Dm00644 build/icons/png/512x512.png $installdir/usr/share/pixmaps/signal-desktop.png
    install -dm00755 $installdir/usr/bin/
    install -dm00644 $installdir/usr/share/signal-desktop/
    cp -R dist/linux-unpacked/* $installdir/usr/share/signal-desktop/
    ln -s /usr/share/signal-desktop/signal-desktop $installdir/usr/bin/signal-desktop
